# Generated by Django 5.2.12 on 2026-03-21 21:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CertificateAuthority",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "certificate_pem",
                    models.TextField(help_text="CA certificate in PEM format"),
                ),
                (
                    "encrypted_private_key",
                    models.BinaryField(help_text="CA private key encrypted at rest (Fernet)"),
                ),
                (
                    "common_name",
                    models.CharField(
                        help_text="Subject Common Name of the CA certificate",
                        max_length=200,
                    ),
                ),
                (
                    "fingerprint",
                    models.CharField(
                        help_text="SHA-256 fingerprint of the CA certificate",
                        max_length=100,
                    ),
                ),
                (
                    "not_valid_before",
                    models.DateTimeField(help_text="Certificate validity start"),
                ),
                (
                    "not_valid_after",
                    models.DateTimeField(help_text="Certificate validity end"),
                ),
                (
                    "key_size",
                    models.IntegerField(
                        default=4096,
                        help_text="RSA key size in bits (2048, 3072, or 4096)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this is the current active CA (only one may be active)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="When this CA was generated"),
                ),
            ],
            options={
                "verbose_name": "Certificate Authority",
                "verbose_name_plural": "Certificate Authorities",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SmtpConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "host",
                    models.CharField(help_text="SMTP server hostname", max_length=255),
                ),
                (
                    "port",
                    models.PositiveIntegerField(
                        default=587,
                        help_text="SMTP port (587 for STARTTLS, 465 for SSL)",
                    ),
                ),
                ("username", models.CharField(blank=True, max_length=255)),
                (
                    "encrypted_password",
                    models.BinaryField(
                        blank=True,
                        default=b"",
                        help_text="SMTP password encrypted at rest (Fernet/SECRET_KEY)",
                    ),
                ),
                (
                    "use_tls",
                    models.BooleanField(default=True, help_text="Use STARTTLS"),
                ),
                (
                    "use_ssl",
                    models.BooleanField(default=False, help_text="Use implicit SSL (port 465)"),
                ),
                (
                    "from_address",
                    models.EmailField(help_text="From address for outgoing emails", max_length=254),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "SMTP configuration",
            },
        ),
        migrations.CreateModel(
            name="ClientCertificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "certificate_pem",
                    models.TextField(help_text="Client certificate in PEM format"),
                ),
                (
                    "encrypted_private_key",
                    models.BinaryField(help_text="Client private key encrypted at rest (Fernet)"),
                ),
                (
                    "common_name",
                    models.CharField(
                        help_text="Subject Common Name (matches the username)",
                        max_length=200,
                    ),
                ),
                (
                    "fingerprint",
                    models.CharField(
                        help_text="SHA-256 fingerprint of the client certificate",
                        max_length=100,
                    ),
                ),
                (
                    "serial_number",
                    models.CharField(help_text="Certificate serial number (hex)", max_length=100),
                ),
                (
                    "key_size",
                    models.IntegerField(
                        default=4096,
                        help_text="RSA key size in bits (2048, 3072, or 4096)",
                    ),
                ),
                (
                    "not_valid_before",
                    models.DateTimeField(help_text="Certificate validity start"),
                ),
                (
                    "not_valid_after",
                    models.DateTimeField(help_text="Certificate validity end"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this certificate is currently active",
                    ),
                ),
                (
                    "revoked",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this certificate has been revoked",
                    ),
                ),
                (
                    "revoked_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this certificate was revoked",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="When this certificate was issued"),
                ),
                (
                    "issuing_ca",
                    models.ForeignKey(
                        help_text="The CA that signed this client certificate",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client_certificates",
                        to="my_tracks.certificateauthority",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user this certificate was issued to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client_certificates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Client Certificate",
                "verbose_name_plural": "Client Certificates",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "device_id",
                    models.CharField(
                        db_index=True,
                        help_text="Unique identifier for the device (from OwnTracks 'tid' field)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Friendly name for the device",
                        max_length=200,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When this device was first registered",
                    ),
                ),
                (
                    "last_seen",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Last time location data was received from this device",
                    ),
                ),
                (
                    "is_online",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the device is currently connected via MQTT",
                    ),
                ),
                (
                    "mqtt_user",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="OwnTracks MQTT user (from topic owntracks/{user}/{device})",
                        max_length=100,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        help_text="Django user who owns this device (matched from mqtt_user)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="devices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Device",
                "verbose_name_plural": "Devices",
                "ordering": ["-last_seen"],
            },
        ),
        migrations.CreateModel(
            name="ServerCertificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "certificate_pem",
                    models.TextField(help_text="Server certificate in PEM format"),
                ),
                (
                    "encrypted_private_key",
                    models.BinaryField(help_text="Server private key encrypted at rest (Fernet)"),
                ),
                (
                    "common_name",
                    models.CharField(
                        help_text="Subject Common Name of the server certificate",
                        max_length=200,
                    ),
                ),
                (
                    "fingerprint",
                    models.CharField(
                        help_text="SHA-256 fingerprint of the server certificate",
                        max_length=100,
                    ),
                ),
                (
                    "san_entries",
                    models.JSONField(
                        default=list,
                        help_text="Subject Alternative Names (IP addresses and DNS names)",
                    ),
                ),
                (
                    "key_size",
                    models.IntegerField(
                        default=4096,
                        help_text="RSA key size in bits (2048, 3072, or 4096)",
                    ),
                ),
                (
                    "not_valid_before",
                    models.DateTimeField(help_text="Certificate validity start"),
                ),
                (
                    "not_valid_after",
                    models.DateTimeField(help_text="Certificate validity end"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this is the current active server certificate",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When this server certificate was generated",
                    ),
                ),
                (
                    "issuing_ca",
                    models.ForeignKey(
                        help_text="The CA that signed this server certificate",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="server_certificates",
                        to="my_tracks.certificateauthority",
                    ),
                ),
            ],
            options={
                "verbose_name": "Server Certificate",
                "verbose_name_plural": "Server Certificates",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "home_latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=10,
                        help_text="Home location latitude — default map center for geofence creation",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "home_longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=10,
                        help_text="Home location longitude — default map center for geofence creation",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "home_label",
                    models.CharField(
                        default="Home",
                        help_text="Display label for the home location pin",
                        max_length=100,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="When this profile was created"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="When this profile was last updated"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="The user this profile belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profiles",
            },
        ),
        migrations.CreateModel(
            name="Waypoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Display name for this geofence (maps to OwnTracks 'desc')",
                        max_length=200,
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        decimal_places=10,
                        help_text="Center latitude of the geofence circle",
                        max_digits=15,
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        decimal_places=10,
                        help_text="Center longitude of the geofence circle",
                        max_digits=15,
                    ),
                ),
                (
                    "radius",
                    models.IntegerField(default=100, help_text="Radius of the geofence circle in metres"),
                ),
                (
                    "rid",
                    models.CharField(
                        help_text="OwnTracks region ID (UUID4); stable across device syncs",
                        max_length=36,
                        unique=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Whether this waypoint is active"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who owns this geofence",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="waypoints",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Waypoint",
                "verbose_name_plural": "Waypoints",
                "ordering": ["label"],
            },
        ),
        migrations.CreateModel(
            name="TransitionAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event",
                    models.CharField(
                        choices=[
                            ("enter", "Enter"),
                            ("leave", "Leave"),
                            ("any", "Either"),
                        ],
                        default="any",
                        help_text="'enter', 'leave', or 'any'",
                        max_length=10,
                    ),
                ),
                (
                    "action_type",
                    models.CharField(choices=[("email", "Email")], default="email", max_length=20),
                ),
                (
                    "email_address",
                    models.EmailField(
                        help_text="Recipient email address for the notification",
                        max_length=254,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Whether this rule is currently active"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transition_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "waypoint",
                    models.ForeignKey(
                        blank=True,
                        help_text="Target waypoint; null means 'any geofence'",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="my_tracks.waypoint",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transition Action",
                "verbose_name_plural": "Transition Actions",
                "ordering": ["waypoint__label", "event"],
            },
        ),
        migrations.CreateModel(
            name="Transition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event",
                    models.CharField(
                        choices=[("enter", "Enter"), ("leave", "Leave")],
                        help_text="'enter' or 'leave'",
                        max_length=10,
                    ),
                ),
                (
                    "region_id",
                    models.CharField(
                        help_text="OwnTracks rid from the transition message",
                        max_length=36,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="OwnTracks desc from the transition message",
                        max_length=200,
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(help_text="When the transition occurred on the device (tst)"),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=10,
                        help_text="Device latitude at transition time",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=10,
                        help_text="Device longitude at transition time",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "accuracy",
                    models.IntegerField(
                        blank=True,
                        help_text="Location accuracy in metres at transition time",
                        null=True,
                    ),
                ),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                (
                    "device",
                    models.ForeignKey(
                        help_text="Device that fired this transition",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transitions",
                        to="my_tracks.device",
                    ),
                ),
                (
                    "waypoint",
                    models.ForeignKey(
                        blank=True,
                        help_text="Matched server-side waypoint (null if rid has no server record)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transitions",
                        to="my_tracks.waypoint",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transition",
                "verbose_name_plural": "Transitions",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        decimal_places=10,
                        help_text="Latitude in decimal degrees (-90 to +90)",
                        max_digits=15,
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        decimal_places=10,
                        help_text="Longitude in decimal degrees (-180 to +180)",
                        max_digits=15,
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True,
                        help_text="Unix timestamp when location was recorded (from 'tst' field)",
                    ),
                ),
                (
                    "accuracy",
                    models.IntegerField(
                        blank=True,
                        help_text="Accuracy of location in meters (from 'acc' field)",
                        null=True,
                    ),
                ),
                (
                    "altitude",
                    models.IntegerField(
                        blank=True,
                        help_text="Altitude above sea level in meters (from 'alt' field)",
                        null=True,
                    ),
                ),
                (
                    "velocity",
                    models.IntegerField(
                        blank=True,
                        help_text="Velocity/speed in km/h (from 'vel' field)",
                        null=True,
                    ),
                ),
                (
                    "battery_level",
                    models.IntegerField(
                        blank=True,
                        help_text="Battery percentage 0-100 (from 'batt' field)",
                        null=True,
                    ),
                ),
                (
                    "connection_type",
                    models.CharField(
                        blank=True,
                        choices=[("w", "WiFi"), ("o", "Offline"), ("m", "Mobile")],
                        help_text="Connection type (from 'conn' field): w=WiFi, o=Offline, m=Mobile",
                        max_length=1,
                    ),
                ),
                (
                    "tracker_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="OwnTracks tracker ID (from 'tid' field)",
                        max_length=10,
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address of the client that submitted this location",
                        null=True,
                    ),
                ),
                (
                    "received_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When the server received this location data",
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        help_text="The device that reported this location",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locations",
                        to="my_tracks.device",
                    ),
                ),
            ],
            options={
                "verbose_name": "Location",
                "verbose_name_plural": "Locations",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["device", "-timestamp"],
                        name="my_tracks_l_device__a6677d_idx",
                    ),
                    models.Index(fields=["-timestamp"], name="my_tracks_l_timesta_2f234e_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="OwnTracksMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        db_index=True,
                        help_text="Type of OwnTracks message (status, lwt, transition, etc.)",
                        max_length=50,
                    ),
                ),
                (
                    "payload",
                    models.JSONField(help_text="Complete message payload as JSON"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address of the client that submitted this message",
                        null=True,
                    ),
                ),
                (
                    "received_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="When the server received this message",
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        blank=True,
                        help_text="The device that sent this message (if identifiable)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="my_tracks.device",
                    ),
                ),
            ],
            options={
                "verbose_name": "OwnTracks Message",
                "verbose_name_plural": "OwnTracks Messages",
                "ordering": ["-received_at"],
                "indexes": [
                    models.Index(
                        fields=["device", "-received_at"],
                        name="my_tracks_o_device__5862db_idx",
                    ),
                    models.Index(
                        fields=["message_type", "-received_at"],
                        name="my_tracks_o_message_941b46_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="waypoint",
            index=models.Index(fields=["user", "is_active"], name="my_tracks_w_user_id_55804a_idx"),
        ),
        migrations.AddIndex(
            model_name="transitionaction",
            index=models.Index(fields=["user", "is_active"], name="ta_user_active_idx"),
        ),
        migrations.AddIndex(
            model_name="transition",
            index=models.Index(fields=["device", "-timestamp"], name="my_tracks_t_device__15c108_idx"),
        ),
        migrations.AddIndex(
            model_name="transition",
            index=models.Index(fields=["waypoint", "-timestamp"], name="my_tracks_t_waypoin_a6e7d7_idx"),
        ),
    ]
