# Generated by Django 6.0.4 on 2026-04-27 13:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("my_tracks", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="device_id",
            field=models.CharField(
                db_index=True,
                help_text="Device identifier sent by OwnTracks (unique per owner)",
                max_length=100,
            ),
        ),
        migrations.AddConstraint(
            model_name="device",
            constraint=models.UniqueConstraint(
                condition=models.Q(("owner__isnull", False)),
                fields=("owner", "device_id"),
                name="unique_device_id_per_owner",
            ),
        ),
    ]
