# Generated by Django 5.2.12 on 2026-03-19 13:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_tracks", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="Django user who owns this device (matched from mqtt_user)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="devices",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="home_label",
            field=models.CharField(
                default="Home",
                help_text="Display label for the home location pin",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="home_latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=10,
                help_text="Home location latitude — default map center for geofence creation",
                max_digits=15,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="home_longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=10,
                help_text="Home location longitude — default map center for geofence creation",
                max_digits=15,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="Waypoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Display name for this geofence (maps to OwnTracks 'desc')",
                        max_length=200,
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        decimal_places=10,
                        help_text="Center latitude of the geofence circle",
                        max_digits=15,
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        decimal_places=10,
                        help_text="Center longitude of the geofence circle",
                        max_digits=15,
                    ),
                ),
                (
                    "radius",
                    models.IntegerField(
                        default=100, help_text="Radius of the geofence circle in metres"
                    ),
                ),
                (
                    "rid",
                    models.CharField(
                        help_text="OwnTracks region ID (UUID4); stable across device syncs",
                        max_length=36,
                        unique=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this waypoint is active"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who owns this geofence",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="waypoints",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Waypoint",
                "verbose_name_plural": "Waypoints",
                "ordering": ["label"],
            },
        ),
        migrations.CreateModel(
            name="Transition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event",
                    models.CharField(
                        choices=[("enter", "Enter"), ("leave", "Leave")],
                        help_text="'enter' or 'leave'",
                        max_length=10,
                    ),
                ),
                (
                    "region_id",
                    models.CharField(
                        help_text="OwnTracks rid from the transition message",
                        max_length=36,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="OwnTracks desc from the transition message",
                        max_length=200,
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        help_text="When the transition occurred on the device (tst)"
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=10,
                        help_text="Device latitude at transition time",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=10,
                        help_text="Device longitude at transition time",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "accuracy",
                    models.IntegerField(
                        blank=True,
                        help_text="Location accuracy in metres at transition time",
                        null=True,
                    ),
                ),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                (
                    "device",
                    models.ForeignKey(
                        help_text="Device that fired this transition",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transitions",
                        to="my_tracks.device",
                    ),
                ),
                (
                    "waypoint",
                    models.ForeignKey(
                        blank=True,
                        help_text="Matched server-side waypoint (null if rid has no server record)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transitions",
                        to="my_tracks.waypoint",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transition",
                "verbose_name_plural": "Transitions",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AddIndex(
            model_name="waypoint",
            index=models.Index(
                fields=["user", "is_active"], name="my_tracks_w_user_id_55804a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transition",
            index=models.Index(
                fields=["device", "-timestamp"], name="my_tracks_t_device__15c108_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transition",
            index=models.Index(
                fields=["waypoint", "-timestamp"], name="my_tracks_t_waypoin_a6e7d7_idx"
            ),
        ),
    ]
