# Generated by Django 5.2.12 on 2026-03-20 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_tracks", "0002_phase9_waypoints_geofencing"),
    ]

    operations = [
        migrations.CreateModel(
            name="SmtpConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "host",
                    models.CharField(help_text="SMTP server hostname", max_length=255),
                ),
                (
                    "port",
                    models.PositiveIntegerField(
                        default=587,
                        help_text="SMTP port (587 for STARTTLS, 465 for SSL)",
                    ),
                ),
                ("username", models.CharField(blank=True, max_length=255)),
                (
                    "encrypted_password",
                    models.BinaryField(
                        blank=True,
                        default=b"",
                        help_text="SMTP password encrypted at rest (Fernet/SECRET_KEY)",
                    ),
                ),
                (
                    "use_tls",
                    models.BooleanField(default=True, help_text="Use STARTTLS"),
                ),
                (
                    "use_ssl",
                    models.BooleanField(
                        default=False, help_text="Use implicit SSL (port 465)"
                    ),
                ),
                (
                    "from_address",
                    models.EmailField(
                        help_text="From address for outgoing emails", max_length=254
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "SMTP configuration",
            },
        ),
    ]
