# Generated by Django 6.0.4 on 2026-04-27 13:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_tracks", "0002_device_unique_per_owner"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="device",
            name="unique_device_id_per_owner",
        ),
        migrations.AddConstraint(
            model_name="device",
            constraint=models.UniqueConstraint(
                fields=("owner", "device_id"), name="unique_device_id_per_owner"
            ),
        ),
    ]
