# Generated by Django 6.0.4 on 2026-04-27 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_tracks", "0003_fix_device_unique_constraint_no_condition"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="last_location_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Last time a GPS location fix was received from this device",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="device",
            name="last_seen",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Last time any MQTT activity was received from this device",
            ),
        ),
    ]
