# Generated by Django 5.2.12 on 2026-03-20 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_tracks", "0003_add_smtpconfig"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TransitionAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event",
                    models.CharField(
                        choices=[
                            ("enter", "Enter"),
                            ("leave", "Leave"),
                            ("any", "Either"),
                        ],
                        default="any",
                        help_text="'enter', 'leave', or 'any'",
                        max_length=10,
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[("email", "Email")], default="email", max_length=20
                    ),
                ),
                (
                    "email_address",
                    models.EmailField(
                        help_text="Recipient email address for the notification",
                        max_length=254,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this rule is currently active"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transition_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "waypoint",
                    models.ForeignKey(
                        blank=True,
                        help_text="Target waypoint; null means 'any geofence'",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="my_tracks.waypoint",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transition Action",
                "verbose_name_plural": "Transition Actions",
                "ordering": ["waypoint__label", "event"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_active"], name="ta_user_active_idx"
                    )
                ],
            },
        ),
    ]
