# Generated by Django 6.0.4 on 2026-04-27 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_tracks", "0004_add_device_last_location_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="received_via",
            field=models.CharField(
                blank=True,
                choices=[("http", "HTTP"), ("mqtt", "MQTT")],
                default="",
                help_text="Transport used to receive this location: 'http' or 'mqtt'",
                max_length=4,
            ),
        ),
    ]
