# Generated by Django 6.0.4 on 2026-04-28 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_tracks", "0006_backfill_location_received_via_mqtt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="waypoint",
            name="rid",
            field=models.CharField(
                help_text=(
                    "Content-derived UUID5 (owner + desc + lat + lon + rad);"
                    " same content always yields the same rid"
                ),
                max_length=36,
                unique=True,
            ),
        ),
    ]
