# Generated by Django 6.0.5 on 2026-05-11 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_tracks", "0008_add_global_automation_rule"),
    ]

    operations = [
        migrations.CreateModel(
            name="LocationQualitySettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "filter_accuracy_enabled",
                    models.BooleanField(
                        default=False,
                        help_text=(
                            "When enabled, ignore fixes whose reported accuracy exceeds "
                            "minimum_accuracy_meters."
                        ),
                    ),
                ),
                (
                    "minimum_accuracy_meters",
                    models.PositiveIntegerField(
                        default=100,
                        help_text=(
                            "Minimum accuracy (meters): use a fix only if accuracy is unknown or "
                            "≤ this value (discard when reported accuracy is greater than this)."
                        ),
                    ),
                ),
            ],
            options={
                "verbose_name": "Location quality settings",
            },
        ),
    ]
