# Generated by Django 6.0.6 on 2026-06-11 16:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("my_tracks", "0014_domesti_bot_user_location_urls"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="last_location_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Last time a GPS location update was received from this device",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="domestibotconfig",
            name="user_location_test_url",
            field=models.CharField(
                blank=True,
                default="",
                help_text=("URL where my-tracks POSTs synthetic test location updates (not live ingest)"),
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="locationqualitysettings",
            name="filter_accuracy_enabled",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "When enabled, ignore location readings whose reported accuracy exceeds minimum_accuracy_meters."
                ),
            ),
        ),
        migrations.AlterField(
            model_name="locationqualitysettings",
            name="minimum_accuracy_meters",
            field=models.PositiveIntegerField(
                default=100,
                help_text=(
                    "Minimum accuracy (meters): use a reading only if accuracy is unknown or "
                    "≤ this value (discard when reported accuracy is greater than this)."
                ),
            ),
        ),
    ]
