# Generated by Django 6.0.6 on 2026-06-26 13:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("my_tracks", "0018_domesti_bot_relay_dedup"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="battery_status",
            field=models.IntegerField(blank=True, help_text="Battery charging state (from 'bs' field)", null=True),
        ),
        migrations.AddField(
            model_name="location",
            name="course",
            field=models.IntegerField(
                blank=True, help_text="Course over ground in degrees (from 'cog' field)", null=True
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="fix_source",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Position source (from 'source' field): gps, network, fused, etc.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="in_regions",
            field=models.JSONField(
                blank=True, help_text="Geofence region names the device was inside (from 'inregions' field)", null=True
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="monitoring_mode",
            field=models.IntegerField(blank=True, help_text="OwnTracks monitoring mode (from 'm' field)", null=True),
        ),
        migrations.AddField(
            model_name="location",
            name="owntracks_created_at",
            field=models.DateTimeField(
                blank=True, help_text="When OwnTracks built the message (from 'created_at' Unix field)", null=True
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="owntracks_message_id",
            field=models.CharField(
                blank=True, default="", help_text="OwnTracks message id (from '_id' field)", max_length=64
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="trigger",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Report trigger (from 't' field): p=ping, r=reportLocation response, u=manual, etc.",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="vertical_accuracy",
            field=models.IntegerField(
                blank=True, help_text="Vertical accuracy in meters (from 'vac' field)", null=True
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="wifi_bssid",
            field=models.CharField(
                blank=True, default="", help_text="WiFi BSSID when conn=w (from 'BSSID' field)", max_length=32
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="wifi_ssid",
            field=models.CharField(
                blank=True, default="", help_text="WiFi SSID when conn=w (from 'SSID' field)", max_length=64
            ),
        ),
    ]
