# Generated by Django 6.0.6 on 2026-06-30 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("my_tracks", "0023_domesti_bot_cooldown_min_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="latest_location",
            field=models.ForeignKey(
                blank=True,
                help_text="Most recent location row for this device (by report time, then fix time)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="my_tracks.location",
            ),
        ),
    ]
