# Generated by Django 6.1.1 on 2026-10-09 02:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("my_tracks", "0024_alter_device_latest_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="domestibotconfig",
            name="activated_pairing_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Protocol 2: id of the pairing that last became active (activation is idempotent per id)",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="domestibotconfig",
            name="outbound_key_verifier",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Protocol 2: keyed HMAC-SHA-256 (hex) of the key domesti-bot presents to my-tracks",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="domestibotconfig",
            name="pending_pairing",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Protocol 2: a staged pairing (id, expiry, encrypted inbound key, outbound verifier, URLs)",
            ),
        ),
        migrations.AddField(
            model_name="domestibotconfig",
            name="previous_outbound_key_expires_at",
            field=models.DateTimeField(
                blank=True, help_text="When the previous outbound verifier stops being accepted", null=True
            ),
        ),
        migrations.AddField(
            model_name="domestibotconfig",
            name="previous_outbound_key_verifier",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Protocol 2: the previous outbound verifier, accepted until previous_outbound_key_expires_at",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="domestibotconfig",
            name="protocol_version",
            field=models.PositiveSmallIntegerField(
                default=1,
                help_text="Relay key protocol: 1 shares one reversible key, 2 keeps a verifier-only outbound key",
            ),
        ),
    ]
