# Generated by Django 5.2.10 on 2026-03-11 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CertificateAuthority",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "certificate_pem",
                    models.TextField(help_text="CA certificate in PEM format"),
                ),
                (
                    "encrypted_private_key",
                    models.BinaryField(
                        help_text="CA private key encrypted at rest (Fernet)"
                    ),
                ),
                (
                    "common_name",
                    models.CharField(
                        help_text="Subject Common Name of the CA certificate",
                        max_length=200,
                    ),
                ),
                (
                    "fingerprint",
                    models.CharField(
                        help_text="SHA-256 fingerprint of the CA certificate",
                        max_length=100,
                    ),
                ),
                (
                    "not_valid_before",
                    models.DateTimeField(help_text="Certificate validity start"),
                ),
                (
                    "not_valid_after",
                    models.DateTimeField(help_text="Certificate validity end"),
                ),
                (
                    "key_size",
                    models.IntegerField(
                        default=4096,
                        help_text="RSA key size in bits (2048, 3072, or 4096)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this is the current active CA (only one may be active)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this CA was generated"
                    ),
                ),
            ],
            options={
                "verbose_name": "Certificate Authority",
                "verbose_name_plural": "Certificate Authorities",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "device_id",
                    models.CharField(
                        db_index=True,
                        help_text="Unique identifier for the device (from OwnTracks 'tid' field)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Friendly name for the device",
                        max_length=200,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When this device was first registered",
                    ),
                ),
                (
                    "last_seen",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Last time location data was received from this device",
                    ),
                ),
                (
                    "is_online",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the device is currently connected via MQTT",
                    ),
                ),
                (
                    "mqtt_user",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="OwnTracks MQTT user (from topic owntracks/{user}/{device})",
                        max_length=100,
                    ),
                ),
            ],
            options={
                "verbose_name": "Device",
                "verbose_name_plural": "Devices",
                "ordering": ["-last_seen"],
            },
        ),
        migrations.CreateModel(
            name="ClientCertificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "certificate_pem",
                    models.TextField(help_text="Client certificate in PEM format"),
                ),
                (
                    "encrypted_private_key",
                    models.BinaryField(
                        help_text="Client private key encrypted at rest (Fernet)"
                    ),
                ),
                (
                    "common_name",
                    models.CharField(
                        help_text="Subject Common Name (matches the username)",
                        max_length=200,
                    ),
                ),
                (
                    "fingerprint",
                    models.CharField(
                        help_text="SHA-256 fingerprint of the client certificate",
                        max_length=100,
                    ),
                ),
                (
                    "serial_number",
                    models.CharField(
                        help_text="Certificate serial number (hex)", max_length=100
                    ),
                ),
                (
                    "key_size",
                    models.IntegerField(
                        default=4096,
                        help_text="RSA key size in bits (2048, 3072, or 4096)",
                    ),
                ),
                (
                    "not_valid_before",
                    models.DateTimeField(help_text="Certificate validity start"),
                ),
                (
                    "not_valid_after",
                    models.DateTimeField(help_text="Certificate validity end"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this certificate is currently active",
                    ),
                ),
                (
                    "revoked",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this certificate has been revoked",
                    ),
                ),
                (
                    "revoked_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this certificate was revoked",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this certificate was issued"
                    ),
                ),
                (
                    "issuing_ca",
                    models.ForeignKey(
                        help_text="The CA that signed this client certificate",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client_certificates",
                        to="my_tracks.certificateauthority",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user this certificate was issued to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client_certificates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Client Certificate",
                "verbose_name_plural": "Client Certificates",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ServerCertificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "certificate_pem",
                    models.TextField(help_text="Server certificate in PEM format"),
                ),
                (
                    "encrypted_private_key",
                    models.BinaryField(
                        help_text="Server private key encrypted at rest (Fernet)"
                    ),
                ),
                (
                    "common_name",
                    models.CharField(
                        help_text="Subject Common Name of the server certificate",
                        max_length=200,
                    ),
                ),
                (
                    "fingerprint",
                    models.CharField(
                        help_text="SHA-256 fingerprint of the server certificate",
                        max_length=100,
                    ),
                ),
                (
                    "san_entries",
                    models.JSONField(
                        default=list,
                        help_text="Subject Alternative Names (IP addresses and DNS names)",
                    ),
                ),
                (
                    "key_size",
                    models.IntegerField(
                        default=4096,
                        help_text="RSA key size in bits (2048, 3072, or 4096)",
                    ),
                ),
                (
                    "not_valid_before",
                    models.DateTimeField(help_text="Certificate validity start"),
                ),
                (
                    "not_valid_after",
                    models.DateTimeField(help_text="Certificate validity end"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this is the current active server certificate",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When this server certificate was generated",
                    ),
                ),
                (
                    "issuing_ca",
                    models.ForeignKey(
                        help_text="The CA that signed this server certificate",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="server_certificates",
                        to="my_tracks.certificateauthority",
                    ),
                ),
            ],
            options={
                "verbose_name": "Server Certificate",
                "verbose_name_plural": "Server Certificates",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this profile was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this profile was last updated"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="The user this profile belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profiles",
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        decimal_places=10,
                        help_text="Latitude in decimal degrees (-90 to +90)",
                        max_digits=15,
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        decimal_places=10,
                        help_text="Longitude in decimal degrees (-180 to +180)",
                        max_digits=15,
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True,
                        help_text="Unix timestamp when location was recorded (from 'tst' field)",
                    ),
                ),
                (
                    "accuracy",
                    models.IntegerField(
                        blank=True,
                        help_text="Accuracy of location in meters (from 'acc' field)",
                        null=True,
                    ),
                ),
                (
                    "altitude",
                    models.IntegerField(
                        blank=True,
                        help_text="Altitude above sea level in meters (from 'alt' field)",
                        null=True,
                    ),
                ),
                (
                    "velocity",
                    models.IntegerField(
                        blank=True,
                        help_text="Velocity/speed in km/h (from 'vel' field)",
                        null=True,
                    ),
                ),
                (
                    "battery_level",
                    models.IntegerField(
                        blank=True,
                        help_text="Battery percentage 0-100 (from 'batt' field)",
                        null=True,
                    ),
                ),
                (
                    "connection_type",
                    models.CharField(
                        blank=True,
                        choices=[("w", "WiFi"), ("o", "Offline"), ("m", "Mobile")],
                        help_text="Connection type (from 'conn' field): w=WiFi, o=Offline, m=Mobile",
                        max_length=1,
                    ),
                ),
                (
                    "tracker_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="OwnTracks tracker ID (from 'tid' field)",
                        max_length=10,
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address of the client that submitted this location",
                        null=True,
                    ),
                ),
                (
                    "received_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When the server received this location data",
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        help_text="The device that reported this location",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locations",
                        to="my_tracks.device",
                    ),
                ),
            ],
            options={
                "verbose_name": "Location",
                "verbose_name_plural": "Locations",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["device", "-timestamp"],
                        name="my_tracks_l_device__a6677d_idx",
                    ),
                    models.Index(
                        fields=["-timestamp"], name="my_tracks_l_timesta_2f234e_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="OwnTracksMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        db_index=True,
                        help_text="Type of OwnTracks message (status, lwt, transition, etc.)",
                        max_length=50,
                    ),
                ),
                (
                    "payload",
                    models.JSONField(help_text="Complete message payload as JSON"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address of the client that submitted this message",
                        null=True,
                    ),
                ),
                (
                    "received_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="When the server received this message",
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        blank=True,
                        help_text="The device that sent this message (if identifiable)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="my_tracks.device",
                    ),
                ),
            ],
            options={
                "verbose_name": "OwnTracks Message",
                "verbose_name_plural": "OwnTracks Messages",
                "ordering": ["-received_at"],
                "indexes": [
                    models.Index(
                        fields=["device", "-received_at"],
                        name="my_tracks_o_device__5862db_idx",
                    ),
                    models.Index(
                        fields=["message_type", "-received_at"],
                        name="my_tracks_o_message_941b46_idx",
                    ),
                ],
            },
        ),
    ]
