# Generated by Django 5.2.10 on 2026-02-20 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_tracks", "0008_alter_location_connection_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="is_online",
            field=models.BooleanField(
                default=False,
                help_text="Whether the device is currently connected via MQTT",
            ),
        ),
    ]
